training:
  num_epochs: 50
  batch_size: 8
  lr: 5.0e-4
  lr_decay: 0.9
  train_split: train_split
  val_split: val_split
model:
  num_classes: 4
  frontend: "resnet50"
  grid_res: 0.5
  pretrained: True,
  img_dims: [1600, 900]
  z_range: [1.0, 6.0, 13.0, 26.0, 51.0]
  h_cropped: [60.0, 60.0, 60.0, 60.0]
  dla_norm: "GroupNorm"
  additions_BEVT_linear: False
  additions_BEVT_conv: False
  dla_l1_n_channels: 32
  n_enc_layers: 2
  n_dec_layers: 2
paths:
  nuscenes: "data/nuscenes"
  unity: "data/unity"
  checkpoints: "checkpoints"
filename: "lemon"